# Generated by Django 5.1.6 on 2025-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnicornCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('industry', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('founded_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
