# Generated by Django 5.1.6 on 2025-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicorncompany',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='deal_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='financial_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='investors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='investors_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='portfolio_exits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unicorncompany',
            name='total_raised',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
